version: '3'
services:
  neobase-mongodb:
    image: mongo:latest
    container_name: neobase-mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: neobase
      MONGO_INITDB_ROOT_PASSWORD: neobase
      MONGO_INITDB_DATABASE: neobase
    volumes:
      - neobase-mongodb-data:/data/db
    networks:
      - neobase-network

  neobase-spreadsheet-postgres:
    image: postgres:16-alpine
    container_name: neobase-spreadsheet-postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: neobase
      POSTGRES_PASSWORD: neobase
      POSTGRES_DB: neobase_spreadsheet_storage
    volumes:
      - neobase-spreadsheet-postgres-data:/var/lib/postgresql/data
    networks:
      - neobase-network

  neobase-redis:
    image: redis:latest
    container_name: neobase-redis
    restart: always
    command: >
      redis-server 
      --aclfile /usr/local/etc/redis/redis.acl
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --stop-writes-on-bgsave-error no
    ports:
      - 6379:6379
    volumes:
      - neobase-redis-data:/data
      - ./redis.acl:/usr/local/etc/redis/redis.acl:ro
    networks:
      - neobase-network

volumes:
  neobase-mongodb-data:
  neobase-redis-data:
  neobase-spreadsheet-postgres-data:

networks:
  neobase-network:
    driver: bridge
    external: true
