version: '3'
services:
  neobase-mongodb:
    image: mongo:latest
    container_name: neobase-mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: neobase
      MONGO_INITDB_ROOT_PASSWORD: neobase
      MONGO_INITDB_DATABASE: neobase
    volumes:
      - neobase-mongodb-data:/data/db
    networks:
      - neobase-network

  neobase-redis:
    image: redis:latest
    container_name: neobase-redis
    restart: always
    command: >
      redis-server 
      --requirepass default
      --user neobase on >default ~* &* +@all
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --stop-writes-on-bgsave-error no
    ports:
      - 6379:6379
    volumes:
      - neobase-redis-data:/data
    networks:
      - neobase-network

volumes:
  neobase-mongodb-data:
  neobase-redis-data:

networks:
  neobase-network:
    driver: bridge
    external: true
