version: '3'
services:
  neobase-mongodb:
    image: mongo:latest
    container_name: neobase-mongodb
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: neobase
      MONGO_INITDB_ROOT_PASSWORD: neobase
      MONGO_INITDB_DATABASE: neobase
    volumes:
      - neobase-mongodb-data:/data/db
    networks:
      - neobase-network

  neobase-redis:
    image: redis:latest
    container_name: neobase-redis
    restart: always
    command: >
      redis-server 
      --aclfile /usr/local/etc/redis/redis.acl
      --maxmemory 512mb
      --maxmemory-policy allkeys-lru
      --stop-writes-on-bgsave-error no
    ports:
      - 6379:6379
    volumes:
      - neobase-redis-data:/data
      - ./redis.acl:/usr/local/etc/redis/redis.acl:ro
    networks:
      - neobase-network

  neobase-spreadsheet-postgres:
    image: postgres:16-alpine
    container_name: neobase-spreadsheet-postgres
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: neobase
      POSTGRES_PASSWORD: neobase
      POSTGRES_DB: neobase_spreadsheet_storage
    volumes:
      - neobase-spreadsheet-postgres-data:/var/lib/postgresql/data
    networks:
      - neobase-network

  neobase-backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: neobase-backend
    restart: always
    ports:
      - 3000:3000
    environment:
      - IS_DOCKER=${IS_DOCKER} # true or false
      - PORT=${PORT} # 3000
      - ENVIRONMENT=${ENVIRONMENT} # DEVELOPMENT, PRODUCTION
      - CORS_ALLOWED_ORIGIN=${CORS_ALLOWED_ORIGIN} # Frontend exposed base url
      - LANDING_PAGE_CORS_ALLOWED_ORIGIN=${LANDING_PAGE_CORS_ALLOWED_ORIGIN} # Landing page exposed base url (optional)
      - MAX_CHATS_PER_USER=${MAX_CHATS_PER_USER} # 0 for trial/development mode(max 2 connection), 1 for unlimited
      - NEOBASE_ADMIN_USERNAME=${NEOBASE_ADMIN_USERNAME} # admin username
      - NEOBASE_ADMIN_PASSWORD=${NEOBASE_ADMIN_PASSWORD} # admin password
      - SCHEMA_ENCRYPTION_KEY=${SCHEMA_ENCRYPTION_KEY} # 32 bytes
      - JWT_SECRET=${JWT_SECRET} # 32 bytes
      - USER_JWT_EXPIRATION_MILLISECONDS=${USER_JWT_EXPIRATION_MILLISECONDS} # 1000 * 60 * 60 * 24 * 30
      - USER_JWT_REFRESH_EXPIRATION_MILLISECONDS=${USER_JWT_REFRESH_EXPIRATION_MILLISECONDS} # 1000 * 60 * 60 * 24 * 30
      - NEOBASE_MONGODB_URI=${NEOBASE_MONGODB_URI} # mongodb://localhost:27017/neobase
      - NEOBASE_MONGODB_NAME=${NEOBASE_MONGODB_NAME} # neobase
      - NEOBASE_REDIS_HOST=${NEOBASE_REDIS_HOST} # neobase-redis
      - NEOBASE_REDIS_PORT=${NEOBASE_REDIS_PORT} # 6379
      - NEOBASE_REDIS_USERNAME=${NEOBASE_REDIS_USERNAME} # neobase
      - NEOBASE_REDIS_PASSWORD=${NEOBASE_REDIS_PASSWORD} # default
      - DEFAULT_LLM_CLIENT=${DEFAULT_LLM_CLIENT} # openai, gemini
      - OPENAI_API_KEY=${OPENAI_API_KEY} # openai api key
      - OPENAI_MODEL=${OPENAI_MODEL} # gpt-j4o
      - OPENAI_MAX_COMPLETION_TOKENS=${OPENAI_MAX_COMPLETION_TOKENS} # 30000
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE} # 1
      - GEMINI_API_KEY=${GEMINI_API_KEY} # gemini api key
      - GEMINI_MODEL=${GEMINI_MODEL} # gemini-2.0-flash
      - GEMINI_MAX_COMPLETION_TOKENS=${GEMINI_MAX_COMPLETION_TOKENS} # 30000
      - GEMINI_TEMPERATURE=${GEMINI_TEMPERATURE} # 1
      - EXAMPLE_DB_TYPE=${EXAMPLE_DB_TYPE} # postgres, clickhouse, mysql, yugabyte...
      - EXAMPLE_DB_HOST=${EXAMPLE_DB_HOST} # localhost
      - EXAMPLE_DB_PORT=${EXAMPLE_DB_PORT} # 5432
      - EXAMPLE_DB_NAME=${EXAMPLE_DB_NAME} # testdb
      - EXAMPLE_DB_USERNAME=${EXAMPLE_DB_USERNAME} # postgres
      - EXAMPLE_DB_PASSWORD=${EXAMPLE_DB_PASSWORD} # postgres
      - SMTP_HOST=${SMTP_HOST} # smtp.gmail.com
      - SMTP_PORT=${SMTP_PORT} # 587
      - SMTP_SECURE=${SMTP_SECURE} # false
      - SMTP_USER=${SMTP_USER} # your-email@gmail.com
      - SMTP_PASSWORD=${SMTP_PASSWORD} # your-app-password
      - SMTP_FROM_NAME=${SMTP_FROM_NAME} # NeoBase - AI Database Copilot
      - SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL} # your-email@gmail.com
      - SPREADSHEET_POSTGRES_HOST=${SPREADSHEET_POSTGRES_HOST} # neobase-spreadsheet-postgres
      - SPREADSHEET_POSTGRES_PORT=${SPREADSHEET_POSTGRES_PORT} # 5432
      - SPREADSHEET_POSTGRES_DATABASE=${SPREADSHEET_POSTGRES_DATABASE} # neobase_spreadsheet_storage
      - SPREADSHEET_POSTGRES_USERNAME=${SPREADSHEET_POSTGRES_USERNAME} # neobase_spreadsheet
      - SPREADSHEET_POSTGRES_PASSWORD=${SPREADSHEET_POSTGRES_PASSWORD} # your_secure_password_here
      - SPREADSHEET_POSTGRES_SSL_MODE=${SPREADSHEET_POSTGRES_SSL_MODE} # disable
      - SPREADSHEET_DATA_ENCRYPTION_KEY=${SPREADSHEET_DATA_ENCRYPTION_KEY} # 32 bytes for AES-GCM
    depends_on:
      - neobase-mongodb
      - neobase-redis
      - neobase-spreadsheet-postgres
    networks:
      - neobase-network

  neobase-client:
    build:
      context: ../client
      dockerfile: Dockerfile
      args: # These are the environment variables for the client
        - VITE_FRONTEND_BASE_URL=${VITE_FRONTEND_BASE_URL}
        - VITE_API_URL=${VITE_API_URL}
        - VITE_ENVIRONMENT=${VITE_ENVIRONMENT}
    container_name: neobase-client
    restart: always
    ports:
      - 5173:5173
    depends_on:
      - neobase-backend
    networks:
      - neobase-network


volumes:
  neobase-mongodb-data:
  neobase-redis-data:
  neobase-spreadsheet-postgres-data:

networks:
  neobase-network:
    driver: bridge
    external: true
